### ISSUE TITLE
Not able to access the looker dashboard plugins from Looker

### ISSUE THREAD

**Issue by shrawanibawage** [looker-open-source/block-cortex-sap#20]
I am not able to see any cortex related plugins in Looker marketplace. Is there an issue or any other way to download the looker dashboards in our instance.

**Comment by chodankarcc** [comment]
Team, We have had downloaded 'Cortex Data Foundation for SAP - Operational Dashboards' from Looker Marketplace and it was working fine. Today when we were unable to update BQ dataset name. We found that 'Cortex Data Foundation for SAP - Operational Dashboards' is no more on Looker Marketplace to install. Can you please check on this?

**Comment by benschuler** [comment]
@99002688 The Looker dashboards are no longer maintained on Looker marketplace, instead you can install the blocks manually via the Git URL ([instructions can be found here](https://cloud.google.com/looker/docs/marketplace#installing_a_tool_from_a_git_url)). You will need to provide the URL of this repository, along with the commit SHA of the version that you'd like to install ([here is the list of our releases in this repository](https://github.com/looker-open-source/block-cortex-sap/releases/)). Please let us know if you are facing any issues with this installation method.

@chodankarcc I saw that you raised your error as a separate issue so will reply there.

**Comment by shrawanibawage** [comment]
Hi @benschuler, thanks for that! I installed using Git URL. I'm seeing all the dashboard values as 0 or 'no results'. Can you specify the exact steps for setting up the user attributes (data type, default values etc). Also are there any other pre installation steps that we might be missing?

**Comment by shrawanibawage** [comment]
Also, some of the dashboards are not available, when I click them it shows: "That page doesn't exist or you don't have permission to view it.
If the URL is correct, check with your admin to make sure you have the correct permissions" 

Following Dashboards I can see this issue: 
6 Accounts Receivable.dashboard.lookml 
6a Day Sales Outstanding.dashboard.lookml 
6b Doubtful Receivable.dashboard.lookml 
6c Overdue Receivable.dashboard.lookml 6d_Total Receivable.dashboard.lookml

**Comment by benschuler** [comment]
Hi @99002688, the general instructions on how to configure user attributes can be found here: https://cloud.google.com/looker/docs/admin-panel-users-user-attributes

For the dashboards in this repository specifically, you want to have one attribute with the name set to `default_value_currency_required` and the label something like `Default Value Currency Required`. Data type needs to be a String and the default value depends on your source data, one acceptable value could be `USD`
The second user attribute that you need to configure is called `client_id_rep`, label can be something like `SAP Client`, data type is also a string and default value depends on your SAP client/mandt value (one example for an acceptable value is `100`).

Having these attributes configured is a prerequisite for the dashboards to show data, since these attributes are controlling the `WHERE` statements of the queries that get triggered.

Regarding your "page does not exist" message, can you check whether these dashboards have been deployed into production? I think we had this behavior in one of our demo instances where after the initial import of the LookML coding, we needed to do a pull from production and then push again via the Looker development IDE in order for the dashboards to properly show up for users.

**Comment by shrawanibawage** [comment]
@benschuler We haven't deployed this in production. Can you help us with the steps. Not able to find documentation for performing this.

Also we have only development systems as it's a demo lab. Do we have any other workaround for this. We have a client demo planned this week. So need this to be working urgently. Let us know ASAP. Thanks!

**Comment by benschuler** [comment]
Hi @99002688, the steps to deploy a LookML project to production are described here: https://cloud.google.com/looker/docs/version-control-and-deploying-changes#getting_your_changes_to_production

`Production` in this context refers to the dashboards being available to end users, so regardless of whether you are using this as a development/demo instance or actual production usage, if you want other users to be able to see your dashboards you'll need to deploy to production following the steps outlined in this guide.

**Comment by benschuler** [comment]
Closing this issue as resolved. If you have any further questions, feel free to raise a new issue here with the specific details.
