### ISSUE TITLE
Issue with Looker Trial and PDT set up

### ISSUE THREAD

**Issue by papiyachatterjee** [looker-open-source/block-cortex-sap#35]
Hi Team,

I have set up a Looker Trial version from Google Console with 30 days validity. I have created the instance and set up the cortex foundation. First issue : The Marketplace is not enabled in the trial version. However I have downloaded from Git and uploaded it . The dashboards work, with one issue of not being able to create the PDT.

I get the error , "Can't construct persistent derived table language_map, connection cortex could not be registered". Any lead would be helpful.

**Comment by benschuler** [comment]
Hi @papiyachatterjee , these sound like generic Looker issues rather than anything specific to our Cortex dashboards. Can you please walk through the steps described in the Looker error guide for your error message and verify that PDT settings are maintained properly? https://cloud.google.com/looker/docs/error-catalog

Especially this one might be helpful for you: https://cloud.google.com/looker/docs/db-config-google-bigquery#persistent_derived_tables_on_a_bigquery_connection

**Comment by benschuler** [comment]
Hi @papiyachatterjee,

I hope that the details provided in my previous response were helpful. Since we have not heard anything back for a while, I assume you were able to get the issues resolved and we can close this issue. If you have any further questions, please feel free to open a new issue and we will be happy to assist you.
