### ISSUE TITLE
Datasets and Accounts Receivable Dashboard

### ISSUE THREAD

**Issue by catrcs** [looker-open-source/block-cortex-sap#4]
Hello, we have two questions:

1- The required customizations are three datasets called "OTC_DATASET", "FINANCE_DATASET" and "FUNCTIONS_DATASET". However, when installing Google Cloud Cortex Framework (https://github.com/GoogleCloudPlatform/cortex-data-foundation) these datasets do not exist. We were able to view the dashboards using the reporting dataset from Google Cloud Cortex Framework on the "OTC_DATASET", "FINANCE_DATASET" and "FUNCTIONS_DATASET" parameters (i.e using the same dataset on all the parameters), but is this the correct configuration?

2 - On the [SAP OTC AR] 06: Accounts Receivable dashboard, one of the visualizations is encountering a query error. Below is the query:

-- raw sql results do not include filled-in values for 'data_intelligence_ar.Current_Date'
SELECT
    (DATE(current_date() , 'Indian/Christmas')) AS data_intelligence_ar_current_date_1
FROM `cortex_test_reporting.AccountingDocumentsReceivables`
     AS data_intelligence_ar
WHERE (data_intelligence_ar.Client_MANDT = "050" )
GROUP BY
    1
ORDER BY
    1 DESC
LIMIT 500

And below is the error:
Query execution failed: - No matching signature for function DATE for argument types: DATE, STRING. Supported signatures: DATE(TIMESTAMP, [STRING]); DATE(DATETIME); DATE(INT64, INT64, INT64); DATE(DATE); DATE(STRING) at [2:6]

Is this a problem related to the query or some configuration is missing?

**Comment by jstuddert** [comment]
Thanks for raising the issue @catrcs!

1/ I see your issue was posted May 10. We've since patched the deployment to simplify the datasets involved and just use the reporting dataset in a default deployment. If this is still an issue for you, can you please re-deploy the latest version of the data foundation and the dashboards and check this again?

2/ As above, given the multiple releases since May 10, could you please check this again once you've deployed the latest version?

If the issue still exists, please provide the latest error messages and steps to reproduce. Thanks for your interest!
